name 'terraria'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Application cookbook which installs and configures a Terraria server.'
long_description 'Application cookbook which installs and configures a Terraria server.'
version '1.0.0'

supports 'ubuntu', '>= 14.04'
supports 'centos', '>= 7.1'
supports 'amazon'

depends 'apt'
depends 'libartifact', '~> 1.3'
depends 'mono'
depends 'rc'
depends 'poise-service'
depends 'ubuntu'
depends 'yum'
depends 'yum-epel'
depends 'yum-centos'
